USERNAME_DOES_NOT_EXIST_ERROR = "username does not exist"
PASSWORD_VALIDATED = "Password is correct. Logging you in"
PASSWORD_NOT_VALIDATED = "Password is incorrect. Please try again"
USERNAME_ALREADY_EXISTS_ERROR = "Username already exists. Please try another username"
PASSWORDS_DONT_MATCH_ERROR = "Passwords do not match, enter again"
REGISTRATION_SUCCESS = "Registration is complete. You can now use Expense Manager"